"""Power stub."""


POWERSTATE_UNKNOWN = -1
POWERSTATE_ON_BATTERY = 0
POWERSTATE_NO_BATTERY = 1
POWERSTATE_CHARGING = 2
POWERSTATE_CHARGED = 3


def get_power_info():
    return (POWERSTATE_UNKNOWN, -1, -1)
